### ISSUE TITLE
NullPointerException when manually adding a license

### ISSUE THREAD

**Issue by timkoers** [oriley-me/homage#10]
I've added the Google Maps Android API licensing info to the library, it worked, but all of a sudden it didn't work anymore and I got a NullPointerException.
This is my code:

```
mHomage.addLicense("another","Google Maps Android API", "https://developers.google.com/maps/documentation/android-api/intro#audience",GoogleApiAvailability.getInstance().getOpenSourceSoftwareLicenseInfo(this));
mHomage.refreshLibraries();
```

This is the stacktrace:
[http://pastebin.com/xJcpL8yc](View trace here)

**Comment by kaneoriley** [comment]
`GoogleApiAvailability.getInstance().getOpenSourceSoftwareLicenseInfo(this)` is returning `null`. The parameter for `addLicense` is marked `NonNull`, so you should check before passing the result to Homage, the `addLicense` code is working as intended.

**Comment by timkoers** [comment]
Googleeeeee :-1: haha, I've added the check. Btw my debug apk has finished building so I will test it now.

**Comment by kaneoriley** [comment]
Lol, in my opinion it should be illegal not to mark a method with nullability annotations (unless it returns a primitive of course). At least then you would have gotten a warning in the IDE.

**Comment by timkoers** [comment]
Exactly, I was thinking Google could do better haha
