### ISSUE TITLE
Change RecyclerView text color

### ISSUE THREAD

**Issue by timkoers** [oriley-me/homage#6]
I can't read the text, because of the (I think) white text color. I suppose you use the primaryTextColor for the textColor? You should add an option to change the textcolor, because mine is and will stay white :-P

Thanks for the great library!

**Comment by kaneoriley** [comment]
Hmmm good point. It is using the text appearance of the theme, but also forcing the card colour to white. So you must be extending from a dark theme? I might just make an attribute to specify whether the card should be dark background/light text or light background/dark text. Not keen on going overboard with custom attributes unless they're absolutely necessary, otherwise I'll lose sight of my original goal of keeping method count to a minimum.

**Comment by timkoers** [comment]
Exactly, I am extending from a Dark Theme in 1 of the themes, but from a Light theme in my other theme. However, both themes have the white background and the white text. The licensing info is barley readable since the background of the TextView is a bit grayish and the text is still white. The icons show up perfectly however.

**Comment by kaneoriley** [comment]
Hmmm. I find it odd the text is white if you're extending a light theme. At any rate, I'll add a parameter to specify dark or light and make sure the text color works based on that setting. Should have an update out tonight :)

**Comment by timkoers** [comment]
Excellent! Thanks

**Comment by kaneoriley** [comment]
No problem. Please star my libraries that you find useful, so they can be more visible and I can see where to focus my time. Every star counts :).

**Comment by timkoers** [comment]
:+1:

**Comment by kaneoriley** [comment]
Let me know how 0.1.1 goes for you :)

**Comment by kaneoriley** [comment]
Actually make that 0.1.2 (noticed a bug in 6.0+ literally 2 minutes after posting 0.1.1 lol).

**Comment by timkoers** [comment]
Haha thanks I will, I've updated the library but I haven't had the chance to test it, my app is acting very strange today.

**Comment by kaneoriley** [comment]
Ah I know them feels. Fingers crossed it starts behaving.

**Comment by timkoers** [comment]
My app started working, yeey, and it might be me that has fixed the issue, but everything is completely visible. 

I don't know if you did fix it with the new code, because I was changing a lot of stuff inside my styles.xml files.

But still thank you!

**Comment by kaneoriley** [comment]
Awesome 😁. The new version has some performance improvements and other things as well, so it's worth upgrading to even if your issue was elsewhere. Glad it's all working for you now.

**Comment by timkoers** [comment]
That's nice man! Btw, expanding the details of the Library doesn't go without any lags. Maybe it's the animator that's messing things up, can't tell.

**Comment by kaneoriley** [comment]
What device/Android version? Maybe make a new issue if you can, and put as much information as possible. It's smooth as for me, but most of my testing is either on a 6P running N preview, or Genymotion.
