### ISSUE TITLE
Expanding the a library's details is lagging

### ISSUE THREAD

**Issue by timkoers** [oriley-me/homage#9]
When expanding a library's details, the animation is lagging.
I am using version 0.1.2 on my OnePlus Two with Android 5.0.1 and my HTC One X with Android 4.2.2.
Both devices run the debug version of my app.

I don't know what the issue is.

**Comment by kaneoriley** [comment]
Are you able to test the Homage sample app on these devices? Will be a good start to narrowing down where the issue lies.

**Comment by timkoers** [comment]
Do you have an apk available?

**Comment by kaneoriley** [comment]
Not on me right now but the sample app is in this repo, should just be a matter of cloning and running `./gradlew :homage-sample:assembleDebug`

**Comment by timkoers** [comment]
Alright let me do this, sorry for the late response, I've got server issues that I'm dealing with overhere.

**Comment by timkoers** [comment]
The debug apk is as smooth as butter, I don't know what the problem is. Let me run my app without the debugger attached

**Comment by kaneoriley** [comment]
Do you have hardware acceleration disabled in your app? That might cause something like this also.

**Comment by timkoers** [comment]
I have specifically enabled it in my app, so that shouldn't be the issue.
EDIT: I am displaying the licensing info in a dialog, could that be the issue?

**Comment by kaneoriley** [comment]
I'm not sure what you mean. Are you using a custom dialog or the built in pop-up mode? Or do you mean the RecyclerView is inside a dialog? Which animation exactly is lagging? Do you have a test apk so I can have a look at what you're referring to?

**Comment by timkoers** [comment]
I am using A RecyclerView inside a dialog, is there a built in pop-up mode? I didn't know about that.
At the moment I don't have a example apk, but I do have a video:  
http://www.mediafire.com/download/1lyvmnuqeu6prrl/homage_sample_video.mp4

**Comment by kaneoriley** [comment]
Hmmm. I can see what you mean. Not sure what the cause is, but it's definitely something to do with how you're displaying it in a dialog. Or possibly the dialog itself. Any reason you don't use a fragment? I have a feeling theres something weird going on with the dialog and RecyclerView that doesn't like the rapid layout size changes caused by the expand/collapse animation.

**Comment by timkoers** [comment]
I think it will be easier to just put it in an activity, don't you think?

**Comment by kaneoriley** [comment]
Either/or. If it was me and I put it in a different activity I'd be using a fragment inside that activity anyway so why not cut out the middle man? But everyones different.

**Comment by kaneoriley** [comment]
Fragment will also use less memory if you embed it in the same activity since only one view will exist at a time, so it's a performance optimisation if you're so inclined.

**Comment by timkoers** [comment]
Hmm, I'll look into it very soon and update you guys on this issue. Thanks for the help so far!

**Comment by timkoers** [comment]
In an activity this problem has been solved! Thanks
